# Generated by Django 4.0.6 on 2022-08-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='Employee')),
                ('avatar', models.FileField(upload_to='', verbose_name='Avatar')),
            ],
        ),
    ]
